import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";
import { useAuth } from "@/hooks/use-auth";
import { ArrowRight, Headphones, Loader2, Mail, UserX } from "lucide-react";
import { Suspense, useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router";

interface AuthProps { redirectAfterAuth?: string; }
function resolveRedirectAfterAuth(returnTo: string | null, fallback = "/dashboard") { return returnTo?.startsWith("/") && !returnTo.startsWith("//") ? returnTo : fallback; }

function Auth({ redirectAfterAuth }: AuthProps = {}) {
  const { isLoading: authLoading, isAuthenticated, signIn } = useAuth(); const navigate = useNavigate(); const [searchParams] = useSearchParams();
  const redirect = resolveRedirectAfterAuth(searchParams.get("returnTo"), redirectAfterAuth); const [step, setStep] = useState<"signIn" | { email: string }>("signIn"); const [otp, setOtp] = useState(""); const [isLoading, setIsLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!authLoading && isAuthenticated) navigate(redirect); }, [authLoading, isAuthenticated, navigate, redirect]);
  const handleEmailSubmit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setIsLoading(true); setError(null); try { const formData = new FormData(event.currentTarget); await signIn("email-otp", formData); setStep({ email: formData.get("email") as string }); } catch (err) { setError(err instanceof Error ? err.message : "Failed to send verification code."); } finally { setIsLoading(false); } };
  const handleOtpSubmit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setIsLoading(true); setError(null); try { await signIn("email-otp", new FormData(event.currentTarget)); navigate(redirect); } catch { setError("The verification code you entered is incorrect."); setOtp(""); } finally { setIsLoading(false); } };
  const handleGuestLogin = async () => { setIsLoading(true); setError(null); try { await signIn("anonymous"); navigate(redirect); } catch (err) { setError(`Failed to sign in: ${err instanceof Error ? err.message : "Unknown error"}`); } finally { setIsLoading(false); } };
  return    <main className="flex min-h-screen items-center justify-center bg-background px-6 py-12"><div className="w-full max-w-md"><button onClick={() => navigate("/")} className="mx-auto mb-8 flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Headphones className="size-5" /></span><span className="text-lg font-bold">sonar<span className="text-primary">.match</span></span></button><p className="mx-auto mb-6 text-xs text-muted-foreground">Your sessions are ephemeral. Your judgment stays.</p><Card className="border-border bg-card shadow-2xl shadow-black/20">{step === "signIn" ? <><CardHeader><CardTitle className="text-2xl">Find your people.</CardTitle><CardDescription>Sign in to discover promoters matched to your music.</CardDescription></CardHeader><form onSubmit={handleEmailSubmit}><CardContent><div className="flex gap-2"><div className="relative flex-1"><Mail className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input name="email" placeholder="you@artist.com" type="email" className="pl-9" disabled={isLoading} required /></div><Button type="submit" size="icon" disabled={isLoading}>{isLoading ? <Loader2 className="size-4 animate-spin" /> : <ArrowRight className="size-4" />}</Button></div>{error && <p className="mt-3 text-sm text-destructive">{error}</p>}<div className="my-6 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border" /> OR <span className="h-px flex-1 bg-border" /></div><Button type="button" variant="outline" className="w-full" onClick={handleGuestLogin} disabled={isLoading}><UserX className="mr-2 size-4" /> Explore as guest</Button></CardContent></form></> : <><CardHeader><CardTitle>Check your email</CardTitle><CardDescription>We've sent a six-digit code to {step.email}</CardDescription></CardHeader><form onSubmit={handleOtpSubmit}><CardContent><input type="hidden" name="email" value={step.email} /><input type="hidden" name="code" value={otp} /><div className="flex justify-center"><InputOTP value={otp} onChange={setOtp} maxLength={6} disabled={isLoading}><InputOTPGroup>{Array.from({ length: 6 }).map((_, index) => <InputOTPSlot key={index} index={index} />)}</InputOTPGroup></InputOTP></div>{error && <p className="mt-3 text-center text-sm text-destructive">{error}</p>}<Button type="submit" className="mt-6 w-full" disabled={isLoading || otp.length !== 6}>{isLoading ? <Loader2 className="mr-2 size-4 animate-spin" /> : null}Verify code <ArrowRight className="ml-2 size-4" /></Button></CardContent><CardFooter><Button type="button" variant="ghost" className="w-full" onClick={() => setStep("signIn")} disabled={isLoading}>Use a different email</Button></CardFooter></form></>}</Card><p className="mt-5 text-center text-xs text-muted-foreground">Your music stays yours. Always.</p></div></main>;
}
export default function AuthPage(props: AuthProps) { return <Suspense><Auth {...props} /></Suspense>; }
