import { motion, useInView } from "framer-motion";
import { ArrowRight, ArrowUpRight, Check, ChevronDown, Disc3, Play, Radio, Sparkles, Target, Users, Waves } from "lucide-react";
import { useRef, useState, type ReactNode } from "react";
import { useNavigate } from "react-router";

const chartPoints = "0 132 18 124 36 126 54 111 72 116 90 93 108 99 126 75 144 82 162 62 180 68 198 44 216 49 234 32 252 38 270 17";
const bars = [24, 40, 32, 54, 45, 70, 58, 82, 68, 94, 78, 100, 86, 92, 72, 84, 61, 74];
const faq = [
  ["What is sonar/match?", "A focused discovery workspace where artists find promoters aligned with their sound, audience, and next release."],
  ["How are matches calculated?", "Your genre, audience direction, location, and campaign intent are compared with each promoter's focus and reach."],
  ["Do I need a label?", "No. sonar/match is built for independent artists and producers who want a sharper route to the right people."],
  ["Can I explore before committing?", "Yes. Explore as a guest, then sign in when you are ready to save your shortlist and request an introduction."],
];

function Reveal({ children, delay = 0, className = "" }: { children: ReactNode; delay?: number; className?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  const visible = useInView(ref, { once: false, amount: 0.18 });
  return (
    <motion.div ref={ref} className={className} initial={{ opacity: 0, y: 28, filter: "blur(8px)" }} animate={visible ? { opacity: 1, y: 0, filter: "blur(0px)" } : { opacity: 0, y: 28, filter: "blur(8px)" }} transition={{ duration: 0.7, delay, ease: [0.22, 1, 0.36, 1] }}>
      {children}
    </motion.div>
  );
}

function SectionLabel({ children }: { children: ReactNode }) {
  return <p className="font-mono text-[10px] uppercase tracking-[.24em] text-[#ff9a52]">{children}</p>;
}

function ProductPreview() {
  const ref = useRef<HTMLDivElement>(null);
  const visible = useInView(ref, { once: false, amount: 0.3 });
  const connections = [["MC", "Maya Chen", "96%", "#ff9a52"], ["LN", "Late Night Radio", "91%", "#c4b5fd"], ["JC", "Juno Collective", "88%", "#89dceb"]];

  return (
    <Reveal delay={0.12} className="relative mx-auto mt-20 max-w-5xl">
      <div className="absolute -inset-5 rounded-[2rem] border border-[#ff9a52]/10 animate-pulse" />
      <div ref={ref} id="signal" className="relative overflow-hidden rounded-2xl border border-white/[.13] bg-[#100e0c]/95 p-4 shadow-2xl shadow-black/60 backdrop-blur-xl sm:p-6">
        <div className="absolute inset-x-1/4 top-0 h-px bg-gradient-to-r from-transparent via-[#ff9a52] to-transparent shadow-[0_0_32px_#ff9a52]" />
        <div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/[.1] pb-5">
          <div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-lg bg-[#ff9a52]/15 text-[#ffad73]"><Radio className="size-4" /></span><div><p className="font-mono text-[9px] uppercase tracking-[.2em] text-white/35">sonar/match workspace</p><p className="mt-1 text-sm font-medium text-white">Your signal is getting clearer</p></div></div>
          <span className="flex items-center gap-2 rounded-full border border-[#a6e3a1]/20 px-3 py-1 font-mono text-[9px] uppercase tracking-wider text-[#a6e3a1]"><span className="size-1.5 rounded-full bg-[#a6e3a1]" /> Live scan</span>
        </div>
        <div className="grid gap-5 py-5 lg:grid-cols-[1.2fr_.8fr]">
          <div className="rounded-xl border border-white/[.1] bg-black/20 p-5"><div className="flex items-start justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-white/35">Release momentum</p><p className="mt-2 text-2xl font-medium text-white">+124% <span className="text-xs text-[#a6e3a1]">this cycle</span></p></div><Target className="size-4 text-[#ff9a52]" /></div><div className="relative mt-5 h-40"><svg viewBox="0 0 270 145" preserveAspectRatio="none" className="absolute inset-0 size-full overflow-visible"><defs><linearGradient id="landingArea" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#ff9a52" stopOpacity=".3" /><stop offset="1" stopColor="#ff9a52" stopOpacity="0" /></linearGradient></defs><path d="M0 132 L18 124 L36 126 L54 111 L72 116 L90 93 L108 99 L126 75 L144 82 L162 62 L180 68 L198 44 L216 49 L234 32 L252 38 L270 17 L270 145 L0 145 Z" fill="url(#landingArea)" opacity={visible ? 1 : 0} /><motion.polyline points={chartPoints} fill="none" stroke="#ff9a52" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" initial={{ pathLength: 0, opacity: 0 }} animate={visible ? { pathLength: 1, opacity: 1 } : { pathLength: 0, opacity: 0 }} transition={{ duration: 1.5, ease: "easeOut" }} /></svg><div className="absolute inset-x-0 bottom-0 border-b border-white/[.1]" /><div className="absolute inset-x-0 top-1/2 border-b border-dashed border-white/[.07]" /></div><div className="flex justify-between font-mono text-[9px] text-white/25"><span>PROFILE</span><span>DISCOVERY</span><span>NOW</span></div></div>
          <div className="rounded-xl border border-white/[.1] bg-black/20 p-5"><div className="flex items-center justify-between"><p className="font-mono text-[9px] uppercase tracking-[.18em] text-white/35">Top connections</p><Users className="size-4 text-[#c4b5fd]" /></div><div className="mt-5 space-y-3">{connections.map(([initials, name, score, color], index) => <motion.div key={name} initial={{ opacity: 0, x: 16 }} animate={visible ? { opacity: 1, x: 0 } : { opacity: 0, x: 16 }} transition={{ delay: .35 + index * .12 }} className="flex items-center gap-3 rounded-lg border border-white/[.08] bg-white/[.035] p-3"><span className="flex size-8 items-center justify-center rounded-md text-[10px] font-bold text-[#100b08]" style={{ backgroundColor: color }}>{initials}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-white">{name}</p><p className="mt-1 font-mono text-[9px] text-white/30">match #{String(index + 1).padStart(2, "0")}</p></div><span className="font-mono text-sm" style={{ color }}>{score}</span></motion.div>)}</div></div>
        </div>
        <div className="flex items-center gap-2 rounded-lg bg-[#a6e3a1]/[.08] px-4 py-3 text-xs text-[#a6e3a1]"><Sparkles className="size-3.5" /> Built from your sound, not vanity metrics.</div>
      </div>
    </Reveal>
  );
}

function BentoCard({ icon, title, text, type }: { icon: ReactNode; title: string; text: string; type: "orbit" | "nodes" | "chart" | "steps" }) {
  return <motion.article whileHover={{ y: -6 }} className="group relative min-h-64 overflow-hidden rounded-2xl border border-white/[.11] bg-[#100e0c] p-6"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_100%,rgba(255,104,31,.18),transparent_35%)] opacity-70 transition duration-500 group-hover:opacity-100" /><div className="relative flex h-full flex-col justify-between"><div><span className="flex size-9 items-center justify-center rounded-lg border border-[#ff9a52]/30 bg-[#ff7a2e]/10 text-[#ffad73]">{icon}</span><h3 className="mt-7 max-w-xs text-2xl font-medium tracking-[-.04em] text-white">{title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-white/40">{text}</p></div><CardVisual type={type} /></div></motion.article>;
}

function CardVisual({ type }: { type: "orbit" | "nodes" | "chart" | "steps" }) {
  if (type === "chart") return <div className="mt-10 flex h-20 items-end gap-1.5">{bars.map((height, index) => <motion.div key={index} initial={{ height: 0 }} whileInView={{ height: `${height}%` }} viewport={{ once: false }} transition={{ delay: index * .04, duration: .45 }} className={`flex-1 rounded-t-sm ${index > 10 ? "bg-[#ff9a52]" : "bg-[#ff9a52]/25"}`} />)}</div>;
  if (type === "steps") return <div className="mt-10 space-y-2">{["Profile tuned", "Promoter matched", "Intro ready"].map((item, index) => <motion.div key={item} initial={{ opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: false }} transition={{ delay: index * .1 }} className="flex items-center gap-3 rounded-lg border border-white/[.09] bg-white/[.03] px-3 py-2"><span className="flex size-5 items-center justify-center rounded-full bg-[#ff9a52] text-[#100b08]"><Check className="size-3" /></span><span className="font-mono text-[10px] uppercase tracking-wider text-white/55">{item}</span><span className="ml-auto text-[10px] text-white/25">0{index + 1}</span></motion.div>)}</div>;
  if (type === "nodes") return <div className="relative mt-8 h-24"><div className="absolute left-1/2 top-1/2 size-10 -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#ff9a52] bg-[#ff9a52]/20 shadow-[0_0_30px_rgba(255,122,46,.4)] animate-pulse" /><div className="absolute left-[18%] top-1/2 h-px w-[64%] bg-gradient-to-r from-transparent via-[#ff9a52]/60 to-transparent" /><div className="absolute left-[15%] top-1/2 size-3 -translate-y-1/2 rounded-full bg-[#c4b5fd]" /><div className="absolute right-[15%] top-1/2 size-3 -translate-y-1/2 rounded-full bg-[#89dceb]" /></div>;
  return <div className="relative mt-8 h-24"><div className="absolute left-1/2 top-1/2 size-20 -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#ff9a52]/30 animate-[spin_10s_linear_infinite]" /><div className="absolute left-1/2 top-1/2 size-11 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#ff9a52] shadow-[0_0_30px_#ff9a52]" /><div className="absolute left-1/2 top-0 h-full w-px bg-[#ff9a52]/30" /><div className="absolute left-0 top-1/2 h-px w-full bg-[#ff9a52]/30" /></div>;
}

export default function Landing() {
  const navigate = useNavigate();
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  return <main className="min-h-screen overflow-hidden bg-[#080706] text-[#eeeae5]"><div className="pointer-events-none fixed inset-0 opacity-40 [background-image:linear-gradient(rgba(255,255,255,.025)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.025)_1px,transparent_1px)] [background-size:62px_62px]" /><div className="pointer-events-none fixed left-1/2 top-[-18rem] h-[34rem] w-[54rem] -translate-x-1/2 rounded-full bg-[#ff6b24]/10 blur-[130px]" />
    <nav className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><button type="button" onClick={() => navigate("/")} className="group flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg border border-[#ff9a52]/50 bg-[#ff7a2e]/10 text-[#ffad73]"><Waves className="size-4" /></span><span className="font-mono text-sm font-bold text-white">SONAR<span className="text-[#ff9a52]">/MATCH</span></span></button><div className="hidden items-center gap-7 md:flex"><a href="#why" className="font-mono text-[10px] uppercase tracking-[.16em] text-white/40 hover:text-white">Why sonar</a><a href="#process" className="font-mono text-[10px] uppercase tracking-[.16em] text-white/40 hover:text-white">Process</a><a href="#faq" className="font-mono text-[10px] uppercase tracking-[.16em] text-white/40 hover:text-white">FAQ</a></div><button type="button" onClick={() => navigate("/auth")} className="group flex items-center gap-2 rounded-full border border-white/[.14] px-4 py-2 font-mono text-[10px] uppercase tracking-[.14em] text-white/65 hover:border-[#ff9a52]/60 hover:text-white">Enter workspace <ArrowUpRight className="size-3.5" /></button></nav>
    <section className="relative mx-auto max-w-7xl px-6 pb-20 pt-24 lg:px-10 lg:pb-32 lg:pt-32"><Reveal className="relative mx-auto max-w-4xl text-center"><SectionLabel><span className="mr-2 inline-block size-1.5 rounded-full bg-[#a6e3a1] shadow-[0_0_12px_#a6e3a1]" /> The artist-to-promoter network</SectionLabel><h1 className="mt-7 text-5xl font-medium leading-[.94] tracking-[-.075em] text-white sm:text-7xl lg:text-[6.5rem]">Make the right<br /><span className="bg-gradient-to-r from-[#ffd2ad] via-[#ff9a52] to-[#e96125] bg-clip-text text-transparent">introduction.</span></h1><p className="mx-auto mt-8 max-w-xl text-base leading-7 text-white/48 sm:text-lg">Find promoters who understand your sound, your scene, and the release you are building next. Less noise. Better signal.</p><div className="mt-10 flex flex-wrap justify-center gap-3"><button type="button" onClick={() => navigate("/auth")} className="group inline-flex items-center gap-3 rounded-full bg-[#ff9a52] px-6 py-3.5 text-sm font-bold text-[#100b08] shadow-[0_0_35px_rgba(255,122,46,.2)] transition hover:bg-[#ffc494] hover:shadow-[0_0_50px_rgba(255,122,46,.38)]">Build my matches <ArrowUpRight className="size-4" /></button><button type="button" onClick={() => document.getElementById("signal")?.scrollIntoView({ behavior: "smooth" })} className="inline-flex items-center gap-2 rounded-full border border-white/[.14] px-6 py-3.5 text-sm font-semibold text-white/60 hover:border-white/30 hover:text-white"><Play className="size-3.5 fill-current" /> See the signal</button></div></Reveal><ProductPreview /><div className="mx-auto mt-10 flex max-w-5xl flex-wrap items-center justify-center gap-x-10 gap-y-3 border-y border-white/[.08] py-5"><span className="font-mono text-[9px] uppercase tracking-[.2em] text-white/25">Built for independent artists</span><span className="text-xs font-semibold text-white/25">PRODUCERS</span><span className="text-xs font-semibold text-white/25">LABELS</span><span className="text-xs font-semibold text-white/25">RADIO</span><span className="text-xs font-semibold text-white/25">CURATORS</span></div></section>
    <section id="why" className="relative mx-auto max-w-7xl px-6 py-24 lg:px-10"><Reveal className="mx-auto max-w-2xl text-center"><SectionLabel>Why artists stick with us</SectionLabel><h2 className="mt-4 text-4xl font-medium tracking-[-.06em] text-white sm:text-5xl">Signal over spectacle.</h2><p className="mt-4 text-sm leading-6 text-white/40">A calmer, sharper way to turn your release into the right conversation.</p></Reveal><div className="mt-14 grid gap-4 md:grid-cols-2"><Reveal delay={.05}><BentoCard icon={<Disc3 />} title="Implementation, not impressions" text="Find people who can create movement around your music, not just inflate a number." type="orbit" /></Reveal><Reveal delay={.12}><BentoCard icon={<Sparkles />} title="High-converting intros" text="Every match gives you context, fit, and a clear reason to reach out." type="nodes" /></Reveal><Reveal delay={.19}><BentoCard icon={<TrendingVisual />} title="Maximum signal" text="Watch your shortlist sharpen as the network learns what your sound needs next." type="chart" /></Reveal><Reveal delay={.26}><BentoCard icon={<ArrowRight />} title="Clear steps and trust" text="Tune your profile. Review the fit. Send the intro. Keep it human." type="steps" /></Reveal></div></section>
    <section id="process" className="border-y border-white/[.08] bg-white/[.018] px-6 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><Reveal className="max-w-xl"><SectionLabel>The process</SectionLabel><h2 className="mt-4 text-4xl font-medium tracking-[-.06em] text-white sm:text-5xl">Fast, clear, done.</h2><p className="mt-4 text-sm leading-6 text-white/40">No maze of forms. No cold database. Just a focused path to your next useful connection.</p></Reveal><div className="mt-14 grid gap-4 md:grid-cols-3">{[["01", "Share your sound", "Give us the genre, energy, and direction behind your next release."], ["02", "Read the fit", "See the people, reach, and context behind every recommendation."], ["03", "Make the intro", "Send a thoughtful request and start a conversation with signal."]].map(([number, title, text], index) => <Reveal key={number} delay={index * .1}><motion.div whileHover={{ y: -6 }} className="relative min-h-64 overflow-hidden rounded-xl border border-white/[.11] bg-[#100e0c] p-6"><span className="font-mono text-5xl text-[#ff9a52]/20">{number}</span><div className="mt-16"><h3 className="text-xl font-medium text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-white/40">{text}</p></div><div className="absolute right-5 top-5 size-16 rounded-full border border-[#ff9a52]/20 animate-[spin_12s_linear_infinite]" /></motion.div></Reveal>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><Reveal className="mx-auto max-w-2xl text-center"><SectionLabel>The room is listening</SectionLabel><h2 className="mt-4 text-4xl font-medium tracking-[-.06em] text-white sm:text-5xl">Better matches feel different.</h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-3">{[["Finally, a shortlist that feels like someone actually listened to the record.", "Nia S.", "Producer / alt R&B"], ["I stopped pitching into the void. The fit context changes everything.", "Kairo M.", "Independent artist"], ["The right promoter is a creative partner. Sonar helped me find that.", "Ari V.", "Electronic artist"]].map(([quote, name, role], index) => <Reveal key={name} delay={index * .1}><motion.div whileHover={{ y: -5 }} className={`h-full rounded-xl border p-6 ${index === 1 ? "border-[#ff9a52]/50 bg-[#ff7a2e]/[.07]" : "border-white/[.1] bg-white/[.025]"}`}><p className="text-base leading-7 text-white/70">&ldquo;{quote}&rdquo;</p><div className="mt-8 border-t border-white/[.1] pt-4"><p className="text-sm font-semibold text-white">{name}</p><p className="mt-1 font-mono text-[9px] uppercase tracking-wider text-white/30">{role}</p></div></motion.div></Reveal>)}</div></section>
    <section id="faq" className="mx-auto max-w-3xl px-6 py-20 lg:px-10"><Reveal className="text-center"><SectionLabel>Questions</SectionLabel><h2 className="mt-4 text-4xl font-medium tracking-[-.06em] text-white">We&apos;ve got answers.</h2></Reveal><div className="mt-10 space-y-2">{faq.map(([question, answer], index) => <Reveal key={question} delay={index * .04}><div className={`overflow-hidden rounded-xl border ${openFaq === index ? "border-[#ff9a52]/60 bg-[#ff7a2e]/[.06]" : "border-white/[.1] bg-white/[.02]"}`}><button type="button" onClick={() => setOpenFaq(openFaq === index ? null : index)} className="flex w-full items-center justify-between px-5 py-4 text-left text-sm font-medium text-white"><span>{question}</span><ChevronDown className={`size-4 text-white/40 transition ${openFaq === index ? "rotate-180 text-[#ff9a52]" : ""}`} /></button>{openFaq === index && <p className="px-5 pb-5 text-sm leading-6 text-white/45">{answer}</p>}</div></Reveal>)}</div></section>
    <section className="mx-auto max-w-7xl px-6 pb-24 pt-10 lg:px-10"><Reveal><div className="relative overflow-hidden rounded-2xl border border-[#ff9a52]/40 bg-[#100e0c] px-7 py-16 text-center shadow-[0_0_80px_rgba(255,122,46,.12)]"><div className="absolute inset-x-1/4 top-0 h-px bg-[#ff9a52] shadow-[0_0_35px_#ff9a52]" /><div className="absolute left-1/2 top-0 size-72 -translate-x-1/2 rounded-full bg-[#ff6b24]/10 blur-[90px] animate-pulse" /><div className="relative"><SectionLabel>Ready when you are</SectionLabel><h2 className="mx-auto mt-4 max-w-2xl text-4xl font-medium tracking-[-.06em] text-white sm:text-6xl">Put your release in the right room.</h2><p className="mx-auto mt-5 max-w-lg text-sm leading-6 text-white/42">Your next connection should feel less like a pitch and more like a fit.</p><button type="button" onClick={() => navigate("/auth")} className="mt-8 inline-flex items-center gap-3 rounded-full bg-[#ff9a52] px-6 py-3.5 text-sm font-bold text-[#100b08] hover:bg-[#ffc494]">Start matching <ArrowUpRight className="size-4" /></button></div></div></Reveal></section>
    <footer className="border-t border-white/[.08] px-6 py-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 sm:flex-row"><p className="font-mono text-xs text-white/35">SONAR<span className="text-[#ff9a52]">/MATCH</span> · make better introductions.</p><p className="font-mono text-[10px] uppercase tracking-wider text-white/25">For artists, not algorithms.</p></div></footer>
  </main>;
}

function TrendingVisual() { return <svg viewBox="0 0 120 34" className="mt-10 h-16 w-full text-[#ff9a52]" fill="none"><path d="M2 28 C18 24 20 29 32 20 S48 22 57 16 S69 20 78 12 S93 17 118 3" stroke="currentColor" strokeWidth="2" /><path d="M2 28 C18 24 20 29 32 20 S48 22 57 16 S69 20 78 12 S93 17 118 3 V34 H2Z" fill="url(#trendFill)" opacity=".18" /><defs><linearGradient id="trendFill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#ff9a52" /><stop offset="1" stopColor="transparent" /></linearGradient></defs></svg>; }
